//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.14 at 02:54:32 AM NZST 
//


package shared.xml.Race;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="CompoundMarkID" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="SeqID" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="Rounding" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ZoneSize" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
public class XMLCorner {

    @XmlAttribute(name = "CompoundMarkID", required = true)
    protected int compoundMarkID;
    @XmlAttribute(name = "SeqID", required = true)
    protected int seqID;
    @XmlAttribute(name = "Rounding", required = true)
    protected String rounding;
    @XmlAttribute(name = "ZoneSize", required = true)
    protected int zoneSize;

    /**
     * Gets the value of the compoundMarkID property.
     * @return Id of the compound mark
     */
    public int getCompoundMarkID() {
        return compoundMarkID;
    }

    /**
     * Sets the value of the compoundMarkID property.
     * @param value sets the id of the compound mark
     */
    public void setCompoundMarkID(int value) {
        this.compoundMarkID = value;
    }

    /**
     * Gets the value of the seqID property.
     * @return the order that the mark is to be passed at
     */
    public int getSeqID() {
        return seqID;
    }

    /**
     * Sets the value of the seqID property.
     * @param value sets the order that this corner is to appear in a race at.
     */
    public void setSeqID(int value) {
        this.seqID = value;
    }

    /**
     * Gets the value of the rounding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRounding() {
        return rounding;
    }

    /**
     * Sets the value of the rounding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRounding(String value) {
        this.rounding = value;
    }

    /**
     * Gets the value of the zoneSize property.
     * @return the size of the leg
     */
    public int getZoneSize() {
        return zoneSize;
    }

    /**
     * Sets the value of the zoneSize property.
     * @param value sets the size of the corner.
     */
    public void setZoneSize(int value) {
        this.zoneSize = value;
    }

}
