//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.14 at 02:54:32 AM NZST 
//


package shared.xml.Race;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="Lat" use="required" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="Lon" use="required" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="SeqID" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
public class XMLLimit {

    @XmlAttribute(name = "Lat", required = true)
    protected double lat;
    @XmlAttribute(name = "Lon", required = true)
    protected double lon;
    @XmlAttribute(name = "SeqID", required = true)
    protected int seqID;

    /**
     * Gets the value of the lat property.
     * @return get the latitude of the limit
     */
    public double getLat() {
        return lat;
    }

    /**
     * Sets the value of the lat property.
     * @param value sets the latitude of the limit
     */
    public void setLat(double value) {
        this.lat = value;
    }

    /**
     * Gets the value of the lon property.
     * @return sets the longitude of the limit
     */
    public double getLon() {
        return lon;
    }

    /**
     * Sets the value of the lon property.
     * @param value sets the longitude of the limit
     */
    public void setLon(double value) {
        this.lon = value;
    }

    /**
     * Gets the value of the seqID property.
     * @return gets the sequence that the limit is at.
     */
    public int getSeqID() {
        return seqID;
    }

    /**
     * Sets the value of the seqID property.
     * @param value sets the order that this limit is to appear in.
     */
    public void setSeqID(int value) {
        this.seqID = value;
    }

}
