//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.14 at 02:54:32 AM NZST 
//


package shared.xml.Race;

import mock.model.collider.Collider;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="SeqId" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="TargetLat" use="required" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="TargetLng" use="required" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *       &lt;attribute name="SourceID" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
public class XMLMark{

    @XmlAttribute(name = "SeqId")
    protected Integer seqId;
    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "TargetLat", required = true)
    protected double targetLat;
    @XmlAttribute(name = "TargetLng", required = true)
    protected double targetLng;
    @XmlAttribute(name = "SourceID", required = true)
    protected int sourceID;

    /**
     * Gets the value of the seqId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSeqId() {
        return seqId;
    }

    /**
     * Sets the value of the seqId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSeqId(Integer value) {
        this.seqId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the targetLat property.
     * @return latitude that mark is at
     */
    public double getTargetLat() {
        return targetLat;
    }

    /**
     * Sets the value of the targetLat property.
     * @param value sets the latitude that the mark is at.
     */
    public void setTargetLat(double value) {
        this.targetLat = value;
    }

    /**
     * Gets the value of the targetLng property.
     * @return the longitude the mark is at
     */
    public double getTargetLng() {
        return targetLng;
    }

    /**
     * Sets the value of the targetLng property.
     * @param value sets the longitude that the value is at
     */
    public void setTargetLng(double value) {
        this.targetLng = value;
    }

    /**
     * Gets the value of the sourceID property.
     * @return the markerboats source ID
     */
    public int getSourceID() {
        return sourceID;
    }

    /**
     * Sets the value of the sourceID property.
     * @param value sets the id of the boat that the mark is referencing to.
     */
    public void setSourceID(int value) {
        this.sourceID = value;
    }

}
