//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.14 at 03:20:03 AM NZST
//


package shared.xml.Race;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RaceID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="RaceType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CreationTimeDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="RaceStartTime"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="Postpone" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="Time" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Participants"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Yacht" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="SourceID" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="Entry" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CompoundMarkSequence"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Corner" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="CompoundMarkID" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="SeqID" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="Rounding" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="ZoneSize" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Course"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="CompoundMark" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Mark" maxOccurs="unbounded"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;attribute name="SeqId" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                                     &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="TargetLat" use="required" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *                                     &lt;attribute name="TargetLng" use="required" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *                                     &lt;attribute name="SourceID" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="CompoundMarkID" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CourseLimit"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Limit" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="Lat" use="required" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *                           &lt;attribute name="Lon" use="required" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *                           &lt;attribute name="SeqID" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "raceID",
        "raceType",
        "creationTimeDate",
        "raceStartTime",
        "participants",
        "compoundMarkSequence",
        "course",
        "courseLimit"
})
@XmlRootElement(name = "Race")
public class XMLRace {

    @XmlElement(name = "RaceID")
    protected int raceID;
    @XmlElement(name = "RaceType", required = true)
    protected String raceType;
    @XmlElement(name = "CreationTimeDate", required = true)
    protected String creationTimeDate;
    @XmlElement(name = "RaceStartTime", required = true)
    protected XMLRaceStartTime raceStartTime;
    @XmlElement(name = "Participants", required = true)
    protected XMLParticipants participants;
    @XmlElement(name = "CompoundMarkSequence", required = true)
    protected XMLCompoundMarkSequence compoundMarkSequence;
    @XmlElement(name = "Course", required = true)
    protected XMLCourse course;
    @XmlElement(name = "CourseLimit", required = true)
    protected XMLCourseLimit courseLimit;

    /**
     * Gets the value of the raceID property.
     * @return the id of the race
     */
    public int getRaceID() {
        return raceID;
    }

    /**
     * Sets the value of the raceID property.
     * @param value sets the id of the race
     */
    public void setRaceID(int value) {
        this.raceID = value;
    }

    /**
     * Gets the value of the raceType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRaceType() {
        return raceType;
    }

    /**
     * Sets the value of the raceType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRaceType(String value) {
        this.raceType = value;
    }

    /**
     * Gets the value of the creationTimeDate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCreationTimeDate() {
        return creationTimeDate;
    }

    /**
     * Sets the value of the creationTimeDate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCreationTimeDate(String value) {
        this.creationTimeDate = value;
    }

    /**
     * Gets the value of the raceStartTime property.
     *
     * @return
     *     possible object is
     *     {@link XMLRaceStartTime }
     *
     */
    public XMLRaceStartTime getRaceStartTime() {
        return raceStartTime;
    }

    /**
     * Sets the value of the raceStartTime property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLRaceStartTime }
     *
     */
    public void setRaceStartTime(XMLRaceStartTime value) {
        this.raceStartTime = value;
    }

    /**
     * Gets the value of the participants property.
     *
     * @return
     *     possible object is
     *     {@link XMLParticipants }
     *
     */
    public XMLParticipants getParticipants() {
        return participants;
    }

    /**
     * Sets the value of the participants property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLParticipants }
     *
     */
    public void setParticipants(XMLParticipants value) {
        this.participants = value;
    }

    /**
     * Gets the value of the compoundMarkSequence property.
     *
     * @return
     *     possible object is
     *     {@link XMLCompoundMarkSequence }
     *
     */
    public XMLCompoundMarkSequence getCompoundMarkSequence() {
        return compoundMarkSequence;
    }

    /**
     * Sets the value of the compoundMarkSequence property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLCompoundMarkSequence }
     *
     */
    public void setCompoundMarkSequence(XMLCompoundMarkSequence value) {
        this.compoundMarkSequence = value;
    }

    /**
     * Gets the value of the course property.
     *
     * @return
     *     possible object is
     *     {@link XMLCourse }
     *
     */
    public XMLCourse getCourse() {
        return course;
    }

    /**
     * Sets the value of the course property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLCourse }
     *
     */
    public void setCourse(XMLCourse value) {
        this.course = value;
    }

    /**
     * Gets the value of the courseLimit property.
     *
     * @return
     *     possible object is
     *     {@link XMLCourseLimit }
     *
     */
    public XMLCourseLimit getCourseLimit() {
        return courseLimit;
    }

    /**
     * Sets the value of the courseLimit property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLCourseLimit }
     *
     */
    public void setCourseLimit(XMLCourseLimit value) {
        this.courseLimit = value;
    }

}
