//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.01 at 10:37:23 PM NZST 
//


package shared.xml.regatta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RegattaID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="RegattaName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CourseName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CentralLatitude" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="CentralLongitude" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="CentralAltitude" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="UtcOffset" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="MagneticVariation" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "regattaID",
    "regattaName",
    "courseName",
    "centralLatitude",
    "centralLongitude",
    "centralAltitude",
    "utcOffset",
    "magneticVariation"
})
@XmlRootElement(name = "RegattaConfig")
public class RegattaConfig {

    @XmlElement(name = "RegattaID")
    protected int regattaID;
    @XmlElement(name = "RegattaName", required = true)
    protected String regattaName;
    @XmlElement(name = "CourseName", required = true)
    protected String courseName;
    @XmlElement(name = "CentralLatitude")
    protected double centralLatitude;
    @XmlElement(name = "CentralLongitude")
    protected double centralLongitude;
    @XmlElement(name = "CentralAltitude")
    protected double centralAltitude;
    @XmlElement(name = "UtcOffset")
    protected double utcOffset;
    @XmlElement(name = "MagneticVariation")
    protected double magneticVariation;

    /**
     * Gets the value of the regattaID property.
     * @return regatta id.
     */
    public int getRegattaID() {
        return regattaID;
    }

    /**
     * Sets the value of the regattaID property.
     * @param value new regatta id.
     */
    public void setRegattaID(int value) {
        this.regattaID = value;
    }

    /**
     * Gets the value of the regattaName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegattaName() {
        return regattaName;
    }

    /**
     * Sets the value of the regattaName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegattaName(String value) {
        this.regattaName = value;
    }

    /**
     * Gets the value of the courseName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * Sets the value of the courseName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseName(String value) {
        this.courseName = value;
    }

    /**
     * Gets the value of the centralLatitude property.
     * @return central latitude.
     */
    public double getCentralLatitude() {
        return centralLatitude;
    }

    /**
     * Sets the value of the centralLatitude property.
     * @param value new central latitude.
     */
    public void setCentralLatitude(double value) {
        this.centralLatitude = value;
    }

    /**
     * Gets the value of the centralLongitude property.
     * @return central longitude.
     */
    public double getCentralLongitude() {
        return centralLongitude;
    }

    /**
     * Sets the value of the centralLongitude property.
     * @param value new central longitude.
     */
    public void setCentralLongitude(double value) {
        this.centralLongitude = value;
    }

    /**
     * Gets the value of the centralAltitude property.
     * @return central altitude.
     */
    public double getCentralAltitude() {
        return centralAltitude;
    }

    /**
     * Sets the value of the centralAltitude property.
     * @param value new central altitude.
     */
    public void setCentralAltitude(double value) {
        this.centralAltitude = value;
    }

    /**
     * Gets the value of the utcOffset property.
     * @return utc offset.
     */
    public double getUtcOffset() {
        return utcOffset;
    }

    /**
     * Sets the value of the utcOffset property.
     * @param value new utc offset.
     */
    public void setUtcOffset(double value) {
        this.utcOffset = value;
    }

    /**
     * Gets the value of the magneticVariation property.
     * @return magnetic variation.
     */
    public double getMagneticVariation() {
        return magneticVariation;
    }

    /**
     * Sets the value of the magneticVariation property.
     * @param value new magnetic variation.
     */
    public void setMagneticVariation(double value) {
        this.magneticVariation = value;
    }

}
